# Generated by Django 2.0.1 on 2018-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userPic',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PostStorage'),
        ),
    ]
