# Generated by Django 2.0.1 on 2018-02-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20180210_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
